### ISSUE TITLE
when i run the solr-recommender-example, i get the following error. Please Help !

### ISSUE THREAD

**Issue by KlwntSingh** [actionml/universal-recommender#10]
java.lang.IllegalArgumentException: Number of columns must be greater then 0! But numberOfColumns = 0
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at org.apache.mahout.math.hadoop.similarity.cooccurrence.RowSimilarityJob$SimilarityReducer.setup(RowSimilarityJob.java:471)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:174)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:649)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

15/04/22 07:08:38 INFO mapred.JobClient:  map 100% reduce 0%
15/04/22 07:08:47 INFO mapred.JobClient:  map 100% reduce 33%
15/04/22 07:08:50 INFO mapred.JobClient: Task Id : attempt_201504212311_0049_r_000000_1, Status : FAILED
java.lang.IllegalArgumentException: Number of columns must be greater then 0! But numberOfColumns = 0
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at org.apache.mahout.math.hadoop.similarity.cooccurrence.RowSimilarityJob$SimilarityReducer.setup(RowSimilarityJob.java:471)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:174)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:649)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

15/04/22 07:08:51 INFO mapred.JobClient:  map 100% reduce 0%
15/04/22 07:09:00 INFO mapred.JobClient:  map 100% reduce 33%
15/04/22 07:09:02 INFO mapred.JobClient: Task Id : attempt_201504212311_0049_r_000000_2, Status : FAILED
java.lang.IllegalArgumentException: Number of columns must be greater then 0! But numberOfColumns = 0
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at org.apache.mahout.math.hadoop.similarity.cooccurrence.RowSimilarityJob$SimilarityReducer.setup(RowSimilarityJob.java:471)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:174)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:649)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

15/04/22 07:09:03 INFO mapred.JobClient:  map 100% reduce 0%
15/04/22 07:09:12 INFO mapred.JobClient:  map 100% reduce 33%
15/04/22 07:09:16 INFO mapred.JobClient:  map 100% reduce 0%
15/04/22 07:09:18 INFO mapred.JobClient: Job complete: job_201504212311_0049
15/04/22 07:09:18 INFO mapred.JobClient: Counters: 23
15/04/22 07:09:18 INFO mapred.JobClient:   Job Counters 
15/04/22 07:09:18 INFO mapred.JobClient:     Launched reduce tasks=4
15/04/22 07:09:18 INFO mapred.JobClient:     SLOTS_MILLIS_MAPS=8837
15/04/22 07:09:18 INFO mapred.JobClient:     Total time spent by all reduces waiting after reserving slots (ms)=0
15/04/22 07:09:18 INFO mapred.JobClient:     Total time spent by all maps waiting after reserving slots (ms)=0
15/04/22 07:09:18 INFO mapred.JobClient:     Launched map tasks=1
15/04/22 07:09:18 INFO mapred.JobClient:     Data-local map tasks=1
15/04/22 07:09:18 INFO mapred.JobClient:     Failed reduce tasks=1
15/04/22 07:09:18 INFO mapred.JobClient:     SLOTS_MILLIS_REDUCES=50583
15/04/22 07:09:18 INFO mapred.JobClient:   FileSystemCounters
15/04/22 07:09:18 INFO mapred.JobClient:     HDFS_BYTES_READ=236
15/04/22 07:09:18 INFO mapred.JobClient:     FILE_BYTES_WRITTEN=59406
15/04/22 07:09:18 INFO mapred.JobClient:   File Input Format Counters 
15/04/22 07:09:18 INFO mapred.JobClient:     Bytes Read=97
15/04/22 07:09:18 INFO mapred.JobClient:   Map-Reduce Framework
15/04/22 07:09:18 INFO mapred.JobClient:     Map output materialized bytes=14
15/04/22 07:09:18 INFO mapred.JobClient:     Combine output records=0
15/04/22 07:09:18 INFO mapred.JobClient:     Map input records=0
15/04/22 07:09:18 INFO mapred.JobClient:     Physical memory (bytes) snapshot=175112192
15/04/22 07:09:18 INFO mapred.JobClient:     Spilled Records=0
15/04/22 07:09:18 INFO mapred.JobClient:     Map output bytes=0
15/04/22 07:09:18 INFO mapred.JobClient:     CPU time spent (ms)=220
15/04/22 07:09:18 INFO mapred.JobClient:     Total committed heap usage (bytes)=131469312
15/04/22 07:09:18 INFO mapred.JobClient:     Virtual memory (bytes) snapshot=746778624
15/04/22 07:09:18 INFO mapred.JobClient:     Combine input records=0
15/04/22 07:09:18 INFO mapred.JobClient:     Map output records=0
15/04/22 07:09:18 INFO mapred.JobClient:     SPLIT_RAW_BYTES=125
15/04/22 07:09:19 INFO mapred.JobClient: Cleaning up the staging area hdfs://localhost:9000/tmp/hadoop-kulwant/mapred/staging/kulwant/.staging/job_201504212311_0050
15/04/22 07:09:19 ERROR security.UserGroupInformation: PriviledgedActionException as:kulwant cause:org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://localhost:9000/user/kulwant/temp/similarityMatrix
Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://localhost:9000/user/kulwant/temp/similarityMatrix
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:235)
    at org.apache.hadoop.mapreduce.lib.input.SequenceFileInputFormat.listStatus(SequenceFileInputFormat.java:55)
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:252)
    at org.apache.hadoop.mapreduce.lib.input.DelegatingInputFormat.getSplits(DelegatingInputFormat.java:115)
    at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1054)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1071)
    at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:550)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:580)
    at org.apache.mahout.cf.taste.hadoop.item.RecommenderJob.run(RecommenderJob.java:249)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at finderbots.recommenders.hadoop.RecommenderUpdateJob.run(RecommenderUpdateJob.java:129)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at finderbots.recommenders.hadoop.RecommenderUpdateJob.main(RecommenderUpdateJob.java:275)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:160)

**Comment by pferrel** [comment]
The Mapreduce version of this has long ago been deprecated and the code replaced with the new version built on Spark, Mahout, and PredictionIO
