### ISSUE TITLE
LLR illegal argument error UR v 0.6.0 using minEventsPerUser

### ISSUE THREAD

**Issue by pferrel** [actionml/universal-recommender#25]
on a large dataset occasionally we get an LLR error. This is probably due to downsampling messing with frequency numbers for LLR. minEventsPerUser wa added in April so this seem odd to be causing a problem now.

This happened about the time of adding numESWriteConnections but this seems an unlikely cause.

```
[INFO] [URModel] Converting cooccurrence matrices into correlators
[INFO] [URModel] Group all properties RDD
[WARN] [TaskSetManager] Lost task 10.0 in stage 101.0 (TID 27265, ip-172-16-1-195.ec2.internal): java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
	at org.apache.mahout.math.stats.LogLikelihood.logLikelihoodRatio(LogLikelihood.java:101)
	at org.apache.mahout.math.cf.SimilarityAnalysis$.logLikelihoodRatio(SimilarityAnalysis.scala:308)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:346)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:339)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1.apply$mcVI$sp(SimilarityAnalysis.scala:339)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:332)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:325)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:34)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:33)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:163)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARN] [TaskSetManager] Lost task 10.1 in stage 101.0 (TID 31939, ip-172-16-1-195.ec2.internal): java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
	at org.apache.mahout.math.stats.LogLikelihood.logLikelihoodRatio(LogLikelihood.java:101)
	at org.apache.mahout.math.cf.SimilarityAnalysis$.logLikelihoodRatio(SimilarityAnalysis.scala:308)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:346)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:339)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1.apply$mcVI$sp(SimilarityAnalysis.scala:339)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:332)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:325)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:34)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:33)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:163)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARN] [TaskSetManager] Lost task 10.2 in stage 101.0 (TID 31940, ip-172-16-3-216.ec2.internal): java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
	at org.apache.mahout.math.stats.LogLikelihood.logLikelihoodRatio(LogLikelihood.java:101)
	at org.apache.mahout.math.cf.SimilarityAnalysis$.logLikelihoodRatio(SimilarityAnalysis.scala:308)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:346)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:339)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1.apply$mcVI$sp(SimilarityAnalysis.scala:339)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:332)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:325)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:34)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:33)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:163)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARN] [TaskSetManager] Lost task 10.3 in stage 101.0 (TID 31941, ip-172-16-1-195.ec2.internal): java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
	at org.apache.mahout.math.stats.LogLikelihood.logLikelihoodRatio(LogLikelihood.java:101)
	at org.apache.mahout.math.cf.SimilarityAnalysis$.logLikelihoodRatio(SimilarityAnalysis.scala:308)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:346)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1$$anonfun$apply$mcVI$sp$1.apply(SimilarityAnalysis.scala:339)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7$$anonfun$apply$1.apply$mcVI$sp(SimilarityAnalysis.scala:339)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:332)
	at org.apache.mahout.math.cf.SimilarityAnalysis$$anonfun$7.apply(SimilarityAnalysis.scala:325)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:34)
	at org.apache.mahout.sparkbindings.blas.MapBlock$$anonfun$exec$2.apply(MapBlock.scala:33)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:163)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[ERROR] [TaskSetManager] Task 10 in stage 101.0 failed 4 times; aborting job
aml@ip-172-16-3-22:~/ur$ 
```

**Comment by ncullen** [comment]
Is the workaround simply avoid "minEventsPerUser" so as to avoid downsampling?
