### ISSUE TITLE
Training Error - "Extracting datasource params. No 'name' is found. "

### ISSUE THREAD

**Issue by ramansv710** [actionml/universal-recommender#65]
Hi All,

I have installed prediction io on MacBook and installed the universal recommender template. I was able to build the app successfully. But, when I do a=n integration test or training on other data, I am getting the below error. I have also copied the engine.json extract. It will be very helpful if anyone share their inputs on this.

engine.json (nothing has been changed. its the default data)

{
  "comment":" This config file uses default settings for all but the required values see README.md for docs",
  "id": "default",
  "description": "Default settings",
  "engineFactory": "com.actionml.RecommendationEngine",
  "datasource": {
    "params" : {
      "name": "sample-handmade-data.txt",
      "appName": "handmade",
      "eventNames": ["purchase", "view", "category-pref"],
      "minEventsPerUser": 3
    }
  },
  "sparkConf": {
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryo.referenceTracking": "false",
    "spark.kryoserializer.buffer": "300m",
    "es.index.auto.create": "true"
  },

Exception when training -

[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.

Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.ParserUtil$.quote(Ljava/lang/String;)Ljava/lang/String;

	at org.json4s.native.JsonMethods$$anonfun$2.apply(JsonMethods.scala:42)

	at org.json4s.native.JsonMethods$$anonfun$2.apply(JsonMethods.scala:42)

	at scala.collection.immutable.List.map(List.scala:284)

	at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:42)

	at org.json4s.native.JsonMethods$.render(JsonMethods.scala:62)

	at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2$$anonfun$2.apply(WorkflowUtils.scala:177)

	at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2$$anonfun$2.apply(WorkflowUtils.scala:168)

	at scala.Option.map(Option.scala:146)

	at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2.apply(WorkflowUtils.scala:168)

	at org.apache.predictionio.workflow.WorkflowUtils$$anonfun$getParamsFromJsonByFieldAndClass$2.apply(WorkflowUtils.scala:159)

	at scala.Option.map(Option.scala:146)

	at org.apache.predictionio.workflow.WorkflowUtils$.getParamsFromJsonByFieldAndClass(WorkflowUtils.scala:159)

	at org.apache.predictionio.controller.Engine.jValueToEngineParams(Engine.scala:363)

	at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:222)

	at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)

	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)

	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)

	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)

	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)

	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)

	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)

	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Regards,
Raman S V

**Comment by ramansv710** [comment]
Very old issue.
