### ISSUE TITLE
Cannot get the recommender queries?

### ISSUE THREAD

**Issue by noa-lab** [actionml/universal-recommender#69]
# I want to get the recommended data correctly.

# Your thoughts and ideas
I followed the steps in the official documentation https://actionml.com/docs/h_ur.
1. Install with docker, no problem, document page: https://actionml.com/docs/harness_container_guide
2. Add the recommendation engine with harness_cli, no problem, the documentation page: https://actionml.com/docs/h_ur_quickstart
3. After the engine is added, the test function is normal.

# Describe your problem
After the data was successfully entered by post and the training was activated, the recommendation engine did not give me feedback.

1
![avatar](https://s2.ax1x.com/2019/11/21/Mh4mvQ.png)
2
![avatar](https://s2.ax1x.com/2019/11/21/MhfXlQ.png)
3
![avatar](https://s2.ax1x.com/2019/11/21/Mh4dbR.png)
The training event was triggered and about 10,000 pieces of data were entered in advance. When the request was routed to the queries, the recommended items were not returned to me. The recommendation engine was running normally, and the log was not reported. I don’t know why.

**Comment by mick912** [comment]
I have same scenario

**Comment by mick912** [comment]
ERROR SparkContextSupport$ - Spark context failed for job JobDescription(321e0ee5-f824-4b72-8589-fcc4e1e2270f,queued,Spark job,Some(Sun Dec 15 08:43:38 GMT 2019),None)
org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:367)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:133)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:120)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by th4m** [comment]
I believe the issue in the original question is that the user John Doe simply doesn't get any recommendations, because there's only one event posted (unless you've omitted other events in your post). If you try to post some more events for more items, you ought to get some recommendations.
E.g. have John Doe buy items a and b, then have Jane Doe buy a. If you query for Jane Doe's recommendations, you should get b.
